#NumPy



## First manipulation
1- Create NumPy array array of size 10, filled with zeros.

2- Create a numpy array with values ranging from 10 to 49

3- Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

4- Create a 3*3*3 numpy matrix, filled with random float values.

5- Given the X python list convert it to an Y numpy array

*texte en italique*

In [69]:
# Import the numpy package under the name np
import numpy as np

In [ ]:
np.zeros(10,dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(3,3,3)

array([[[0.99038235, 0.89043733, 0.67623377],
        [0.6327861 , 0.65170817, 0.135325  ],
        [0.49638893, 0.9480433 , 0.12476884]],

       [[0.78105903, 0.50339934, 0.02305623],
        [0.68856863, 0.01723815, 0.21629374],
        [0.16120841, 0.8965063 , 0.28084847]],

       [[0.8698597 , 0.34636831, 0.09335489],
        [0.5829235 , 0.06714623, 0.50447103],
        [0.64241051, 0.95943634, 0.88497309]]])

In [ ]:
X=[2,5,7,9]

Y= np.array(X)
Y

array([2, 5, 7, 9])

## Array indexation

1. Given the X numpy array, show it's first element
2. Given the X numpy array, show it's last element
3. Given the X numpy array, show it's first three elements
4. Given the X numpy array, show the elements in reverse position
5. Given the X numpy array, show the elements in an odd position
6. Given the Y numpy matrix, show the first two elements on the first two rows


In [70]:
X = np.array([1,2,3,9,14,17,96,9])


In [ ]:
X[0]

1

In [ ]:
X[-1]

4

In [ ]:
X[:3]

array([1, 2, 3])

In [ ]:
X[::-1]

array([4, 3, 2, 1])

In [ ]:
Y = np.random.randint(low=1,high=11,size=(4,5))
print(Y)

[[1 8 8 5 8]
 [7 5 6 1 6]
 [4 3 1 9 8]
 [6 8 5 7 7]]


In [ ]:
Y[:2]

array([[1, 8, 8, 5, 8],
       [7, 5, 6, 1, 6]])

## Array manipulation

2. Reverse the given numpy array (first element becomes last)
3. Order (sort) the given numpy array
4. Given the X numpy array, return True if any of its elements is zero
5. Given the X numpy array, return True if none of its elements is zero

In [ ]:
X[::-1]

array([4, 3, 2, 1])

In [ ]:
Z = np.array([11,7,2,5,6,14])
Z.sort()
Z

array([ 2,  5,  6,  7, 11, 14])

In [ ]:
np.all(Z!=0)

True

## Summary statistics
1. Given the X numpy array, show the sum of its elements
2. Given the X numpy array, show the mean value of its elements
3. Given the X numpy matrix, show the sum of its columns
4. Given the X numpy matrix, show the mean value of its rows
5. Given the X numpy array, show the max value of its elements

In [28]:
X.sum()

151

In [29]:
X.mean()

18.875

In [31]:
#column
X = np.array([[ 2,  7, 10,  8,  7],
       [ 4,  8,  4,  1,  3],
       [ 9, -1, -1,  9, -1],
       [ 9, -1, 10,  1,  4],
       [ 1,  1,  1,  1,  1]])


X.sum(axis=1)

array([34, 20, 15, 23,  5])

In [ ]:
#rows 
X.mean(axis=1)

array([6.8, 4. , 3. , 4.6, 1. ])

# Pandas



## Series creation
1. Create an empty pandas Series
2. Given the X python list convert it to an Y pandas Series
3. Given the X pandas Series, name it 'My letters'
4. Given the X pandas Series, show its values

In [34]:
import pandas as pd
X= [1,2,3,4]
series=pd.Series(X)

series

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
# your code goes here


In [ ]:
# your code goes here
series.name="My letters"
series

0    1
1    2
2    3
3    4
Name: My letters, dtype: int64

In [ ]:
# your code goes here
series.values

array([1, 2, 3, 4])

## Series indexation
1. Assign index names to the given X pandas Series
2. Given the X pandas Series, show its first element
3. Given the X pandas Series, show the elements in reverse position
4. Reverse the given pandas Series (first element becomes last)
5. Order (sort) the given pandas Series
6. Given the X pandas Series, set the fifth element equal to 10

In [38]:
s= pd.Series([1,2,3,7,45,8,9])

s.index= ["A","B","C","D","E","F","G"]

s

A     1
B     2
C     3
D     7
E    45
F     8
G     9
dtype: int64

In [39]:
s.name = "pds"
s

A     1
B     2
C     3
D     7
E    45
F     8
G     9
Name: pds, dtype: int64

In [40]:
s[0]

1

In [41]:
s[::-1]

G     9
F     8
E    45
D     7
C     3
B     2
A     1
Name: pds, dtype: int64

In [42]:
#s.sort_values()
s.sort_values()


A     1
B     2
C     3
D     7
F     8
G     9
E    45
Name: pds, dtype: int64

In [43]:
s[4]=5

## Pandas DataFrames
1. Create an empty pandas DataFrame


In [44]:
pd.DataFrame(data=[None],
             index=[None],
             columns=[None])

NaN
NaN  None

2. Create a marvel_df pandas DataFrame with the given marvel data

In [56]:

marvel_data = [
    ['Spider-Man', 'male', 1962],
    ['Captain America', 'male', 1941],
    ['Wolverine', 'male', 1974],
    ['Iron Man', 'male', 1963],
    ['Thor', 'male', 1963],
    ['Thing', 'male', 1961],
    ['Mister Fantastic', 'male', 1961],
    ['Hulk', 'male', 1962],
    ['Beast', 'male', 1963],
    ['Invisible Woman', 'female', 1961],
    ['Storm', 'female', 1975],
    ['Namor', 'male', 1939],
    ['Hawkeye', 'male', 1964],
    ['Daredevil', 'male', 1964],
    ['Doctor Strange', 'male', 1963],
    ['Hank Pym', 'male', 1962],
    ['Scarlet Witch', 'female', 1964],
    ['Wasp', 'female', 1963],
    ['Black Widow', 'female', 1964],
    ['Vision', 'male', 1968]
]

In [57]:
df=pd.DataFrame(marvel_data)

df


0       1     2
0         Spider-Man    male  1962
1    Captain America    male  1941
2          Wolverine    male  1974
3           Iron Man    male  1963
4               Thor    male  1963
5              Thing    male  1961
6   Mister Fantastic    male  1961
7               Hulk    male  1962
8              Beast    male  1963
9    Invisible Woman  female  1961
10             Storm  female  1975
11             Namor    male  1939
12           Hawkeye    male  1964
13         Daredevil    male  1964
14    Doctor Strange    male  1963
15          Hank Pym    male  1962
16     Scarlet Witch  female  1964
17              Wasp  female  1963
18       Black Widow  female  1964
19            Vision    male  1968

3. Add column names to the marvel_df

In [58]:
df.columns=["Name","Gender","yearOfRelease"]
df

Name  Gender  yearOfRelease
0         Spider-Man    male           1962
1    Captain America    male           1941
2          Wolverine    male           1974
3           Iron Man    male           1963
4               Thor    male           1963
5              Thing    male           1961
6   Mister Fantastic    male           1961
7               Hulk    male           1962
8              Beast    male           1963
9    Invisible Woman  female           1961
10             Storm  female           1975
11             Namor    male           1939
12           Hawkeye    male           1964
13         Daredevil    male           1964
14    Doctor Strange    male           1963
15          Hank Pym    male           1962
16     Scarlet Witch  female           1964
17              Wasp  female           1963
18       Black Widow  female           1964
19            Vision    male           1968


4. Add index names to the marvel_df (use the character name as index)




In [59]:
df.set_index("Name")


Gender  yearOfRelease
Name                                   
Spider-Man          male           1962
Captain America     male           1941
Wolverine           male           1974
Iron Man            male           1963
Thor                male           1963
Thing               male           1961
Mister Fantastic    male           1961
Hulk                male           1962
Beast               male           1963
Invisible Woman   female           1961
Storm             female           1975
Namor               male           1939
Hawkeye             male           1964
Daredevil           male           1964
Doctor Strange      male           1963
Hank Pym            male           1962
Scarlet Witch     female           1964
Wasp              female           1963
Black Widow       female           1964
Vision              male           1968

## DataFrame selection, slicing and indexation

1. Show the first 5 elements on marvel_df

In [60]:
df.head()

Name Gender  yearOfRelease
0       Spider-Man   male           1962
1  Captain America   male           1941
2        Wolverine   male           1974
3         Iron Man   male           1963
4             Thor   male           1963

2. Show the last 5 elements on marvel_df


In [61]:
df.tail()

Name  Gender  yearOfRelease
15       Hank Pym    male           1962
16  Scarlet Witch  female           1964
17           Wasp  female           1963
18    Black Widow  female           1964
19         Vision    male           1968

3. Show just the gender of the first 5 elements on marvel_df

In [62]:
df.Gender

0       male
1       male
2       male
3       male
4       male
5       male
6       male
7       male
8       male
9     female
10    female
11      male
12      male
13      male
14      male
15      male
16    female
17    female
18    female
19      male
Name: Gender, dtype: object

## DataFrame manipulation and operations

1. Modify the first_appearance of 'Vision' to year 1964

In [63]:
df.loc["Vision","yearOfRelease"]=1964
df

Name  Gender  yearOfRelease
0             Spider-Man    male         1962.0
1        Captain America    male         1941.0
2              Wolverine    male         1974.0
3               Iron Man    male         1963.0
4                   Thor    male         1963.0
5                  Thing    male         1961.0
6       Mister Fantastic    male         1961.0
7                   Hulk    male         1962.0
8                  Beast    male         1963.0
9        Invisible Woman  female         1961.0
10                 Storm  female         1975.0
11                 Namor    male         1939.0
12               Hawkeye    male         1964.0
13             Daredevil    male         1964.0
14        Doctor Strange    male         1963.0
15              Hank Pym    male         1962.0
16         Scarlet Witch  female         1964.0
17                  Wasp  female         1963.0
18           Black Widow  female         1964.0
19                Vision    male         1968.0
Vision               NaN     NaN         1964.0

2. Add a new column to marvel_df called 'years_since' with the years since first_appearance

In [64]:

df["first_appearance"]= 2022-df["yearOfRelease"]
df

Name  Gender  yearOfRelease  first_appearance
0             Spider-Man    male         1962.0              60.0
1        Captain America    male         1941.0              81.0
2              Wolverine    male         1974.0              48.0
3               Iron Man    male         1963.0              59.0
4                   Thor    male         1963.0              59.0
5                  Thing    male         1961.0              61.0
6       Mister Fantastic    male         1961.0              61.0
7                   Hulk    male         1962.0              60.0
8                  Beast    male         1963.0              59.0
9        Invisible Woman  female         1961.0              61.0
10                 Storm  female         1975.0              47.0
11                 Namor    male         1939.0              83.0
12               Hawkeye    male         1964.0              58.0
13             Daredevil    male         1964.0              58.0
14        Doctor Strange    male         1963.0              59.0
15              Hank Pym    male         1962.0              60.0
16         Scarlet Witch  female         1964.0              58.0
17                  Wasp  female         1963.0              59.0
18           Black Widow  female         1964.0              58.0
19                Vision    male         1968.0              54.0
Vision               NaN     NaN         1964.0              58.0

3. Given the marvel_df pandas DataFrame, make a mask showing the female characters

In [65]:
df[df.Gender=="female"]

Name  Gender  yearOfRelease  first_appearance
9   Invisible Woman  female         1961.0              61.0
10            Storm  female         1975.0              47.0
16    Scarlet Witch  female         1964.0              58.0
17             Wasp  female         1963.0              59.0
18      Black Widow  female         1964.0              58.0

4. Given the marvel_df pandas DataFrame, get the characters with first_appearance after 1970

In [66]:
df[df.yearOfRelease>1970]

Name  Gender  yearOfRelease  first_appearance
2   Wolverine    male         1974.0              48.0
10      Storm  female         1975.0              47.0

## DataFrame summary statistics

1. Show basic statistics of marvel_df

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21 entries, 0 to Vision
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Name              20 non-null     object 
 1   Gender            20 non-null     object 
 2   yearOfRelease     21 non-null     float64
 3   first_appearance  21 non-null     float64
dtypes: float64(2), object(2)
memory usage: 1.4+ KB


2. Given the marvel_df pandas DataFrame, show the mean value of first_appearance

In [ ]:
df.describe()

yearOfRelease
count      21.000000
mean     1961.761905
std         8.104966
min      1939.000000
25%      1962.000000
50%      1963.000000
75%      1964.000000
max      1975.000000

3. Given the marvel_df pandas DataFrame, show the min value of first_appearance

In [68]:
df.yearOfRelease.min()

1939.0